"""PDF Export functionality for research reports."""

import markdown
import logging
from io import BytesIO

logger = logging.getLogger("PDFExporter")

# CSS for PDF styling
PDF_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&family=Inter:wght@400;600&display=swap');

body {
    font-family: 'Merriweather', Georgia, serif;
    font-size: 11pt;
    line-height: 1.7;
    color: #1a1a1a;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
}

h1 {
    font-family: 'Inter', sans-serif;
    font-size: 24pt;
    font-weight: 600;
    color: #0a0a0a;
    border-bottom: 2px solid #e0e0e0;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

h2 {
    font-family: 'Inter', sans-serif;
    font-size: 18pt;
    font-weight: 600;
    color: #1a1a1a;
    margin-top: 30px;
}

h3 {
    font-family: 'Inter', sans-serif;
    font-size: 14pt;
    font-weight: 600;
    color: #2a2a2a;
}

p {
    margin-bottom: 12px;
    text-align: justify;
}

ul, ol {
    margin-left: 20px;
    margin-bottom: 15px;
}

li {
    margin-bottom: 6px;
}

code {
    font-family: 'Consolas', monospace;
    background: #f4f4f4;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 10pt;
}

pre {
    background: #f8f8f8;
    padding: 15px;
    border-radius: 5px;
    overflow-x: auto;
    border: 1px solid #e0e0e0;
}

blockquote {
    border-left: 4px solid #cba45d;
    padding-left: 15px;
    margin-left: 0;
    color: #4a4a4a;
    font-style: italic;
}

a {
    color: #2563eb;
    text-decoration: none;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
}

th, td {
    border: 1px solid #ddd;
    padding: 10px;
    text-align: left;
}

th {
    background: #f4f4f4;
    font-weight: 600;
}

.footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #e0e0e0;
    font-size: 9pt;
    color: #666;
    text-align: center;
}
"""


def generate_pdf(report_markdown: str, title: str = "Research Report") -> bytes:
    """Convert Markdown report to PDF bytes."""
    try:
        from weasyprint import HTML, CSS
        
        # Convert Markdown to HTML
        html_content = markdown.markdown(
            report_markdown,
            extensions=['tables', 'fenced_code', 'toc']
        )
        
        # Wrap in full HTML document
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{title}</title>
        </head>
        <body>
            {html_content}
            <div class="footer">
                Generated by Deep Research Agent
            </div>
        </body>
        </html>
        """
        
        # Generate PDF
        pdf_buffer = BytesIO()
        HTML(string=full_html).write_pdf(
            pdf_buffer,
            stylesheets=[CSS(string=PDF_CSS)]
        )
        pdf_buffer.seek(0)
        
        logger.info(f"📄 Generated PDF: {len(pdf_buffer.getvalue())} bytes")
        return pdf_buffer.getvalue()
        
    except ImportError:
        logger.error("WeasyPrint not installed. Using fallback.")
        # Fallback: return HTML as bytes (user can print to PDF)
        html_bytes = f"<html><body>{markdown.markdown(report_markdown)}</body></html>".encode()
        return html_bytes
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise
